CREATE TABLE IF NOT EXISTS `ActorAward` (
  `AwardID` INTEGER PRIMARY KEY AUTOINCREMENT,
  `body` VARCHAR(30) NOT NULL,
  `AwardName` VARCHAR(50) NOT NULL,
  `year` VARCHAR(4) NOT NULL,
  `ActorID` INTEGER NOT NULL,
  FOREIGN KEY (`ActorID`) REFERENCES `Actor`(`ActorID`)
);