CREATE TABLE IF NOT EXISTS `MovieAward` (
  `AwardID` INTEGER PRIMARY KEY AUTOINCREMENT,
  `body` VARCHAR(30) NOT NULL,
  `AwardName` VARCHAR(50) NOT NULL,
  `year` VARCHAR(4) NOT NULL,
  `MovieID` INTEGER,
  FOREIGN KEY (`MovieID`) REFERENCES `Movie`(`MovieID`)
);